services:
    server:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        ports:
            - 5000:5000
    gateway:
        build:
            dockerfile: Dockerfile.dev
            context: ./gateway
        ports:
            - 80:80

    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - 3000:3000