services:
    server:
        build: server
        volumes:
            - /app/node_modules
            - ./server:/app
        ports:
            - 5000:5000
    gateway:
        build: gateway
        ports:
            - 80:80

    client:
        build: client
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - 3000:3000